# 연습문제
# NumPy Exercise - 1 : 기온 분석
* 기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은 언제였고, 몇도인가요?
* 역사적으로 일교차가 가장 큰 날짜는 몇년 몇월 몇일 인가요?
* 1년 중 평균적으로 일교차가 가장 큰 날짜는 몇월 몇일 인가요?
* 가장 덥다고 알려진 대구보다 서울이 더 더운날이 가장 많은 연도는 언제인가요?

날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃)

In [6]:
import numpy as np

# 날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃)
seoul = np.loadtxt("./data/seoul.csv", dtype=np.object, 
                 delimiter=',', skiprows=1)
daegu = np.loadtxt("./data/daegu.csv", dtype=np.object, 
                 delimiter=',', skiprows=1, encoding="utf-8")

In [14]:
# 서울
# 날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃)
for row in seoul:
    if row[2] == '': # 평균기온
        row[2] = -999      
    else:
        row[2] = float(row[2]) 
    if row[3] == '': # 최저기온
        row[3] = -999      
    else:
        row[3] = float(row[3]) 
    if row[4] == '': # 최고기온
        row[4] = 999      
    else:
        row[4] = float(row[4]) 
print(seoul)

[['1907-10-01' '108' 13.5 7.9 20.7]
 ['1907-10-02' '108' 16.2 7.9 22.0]
 ['1907-10-03' '108' 16.2 13.1 21.3]
 ...
 ['2020-09-04' '108' 23.3 19.9 27.5]
 ['2020-09-05' '108' 23.3 19.2 27.3]
 ['2020-09-06' '108' 21.7 19.5 24.4]]

## 1. 기상 관측 이래, 서울의 최고 기온이 가장 높았던 날은 언제였고, 몇도인가요?

In [16]:
max_temp = -999     # 최고 기온 값
max_date = ''       # 최고 기온 날짜

# 날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃)
for row in seoul:
    if row[4] != 999 and row[4] >= max_temp:
        max_temp = row[4] 
        max_date = row[0]
#         print(max_date, max_temp)
        
print(max_date, max_temp)

2018-08-01 39.6

### for문 안쓰고 풀기 (예시 답안)

- 데이터 분석을 진행할 때 데이터의 전처리가 진행되어야 한다.
- 결측치 처리와 이상치 처리를 해야 한다.
- **결측치 처리**
    - raw 데이터는 문제의 소지가 있을 수 있다.
    - 데이터가 없는 경우를 의미
    - 삭제/ 평균,최고, 최저 등으로 값 대체
- **이상치 처리**
    - 데이터는 존재하는데 정상범위가 아닌 데이터
    - 삭제하거나 대체

In [1]:
import numpy as np

seoul2 = np.loadtxt("./data/seoul.csv", dtype=np.object, delimiter=',', skiprows=1)
print(seoul2)

[['1907-10-01' '108' '13.5' '7.9' '20.7']
 ['1907-10-02' '108' '16.2' '7.9' '22']
 ['1907-10-03' '108' '16.2' '13.1' '21.3']
 ...
 ['2020-09-04' '108' '23.3' '19.9' '27.5']
 ['2020-09-05' '108' '23.3' '19.2' '27.3']
 ['2020-09-06' '108' '21.7' '19.5' '24.4']]

In [19]:
print(seoul2.T)

[['1907-10-01' '1907-10-02' '1907-10-03' ... '2020-09-04' '2020-09-05'
  '2020-09-06']
 ['108' '108' '108' ... '108' '108' '108']
 ['13.5' '16.2' '16.2' ... '23.3' '23.3' '21.7']
 ['7.9' '7.9' '13.1' ... '19.9' '19.2' '19.5']
 ['20.7' '22' '21.3' ... '27.5' '27.3' '24.4']]

In [9]:
# 최고 기온 
# 최고온도를 알아내서 boolean indexing으로 날짜를 알아낼 수 있다.
high_temp_seoul = seoul2.T[4]
print(high_temp_seoul)
# ['20.7' '22' '21.3' ... '27.5' '27.3' '24.4']

# 결측치 Boolean Mask
print(high_temp_seoul == '')
print((high_temp_seoul == '').sum())  # 758개

['20.7' '22' '21.3' ... '27.5' '27.3' '24.4']
[False False False ... False False False]
758

In [14]:
# 결측치 삭제
# boolean indexing을 이용해서 ''가 아닌 최고기온만 뽑아낸다.
high_temp_seoul[high_temp_seoul != '']
# array(['20.7', '22', '21.3', ..., '27.5', '27.3', '24.4'], dtype=object)

high_temp = high_temp_seoul[high_temp_seoul != ''].astype(np.float64).max() # 39.6

In [18]:
# 최고 기온을 알아냈으니, 최고 기온의 날짜 알아내기

# 최고기온 ndarray 안에서, 위에서 구한 최고 기온에 대한 boolean mask 만들기
print(high_temp_seoul == str(high_temp))  # 최대값만 True고 나머지는 False
print(seoul2.T[0][high_temp_seoul == str(high_temp)]) # 중복처리도 자동으로 됨

[False False False ... False False False]
['2018-08-01']

## 2. 역사적으로 일교차가 가장 큰 날짜는 몇년 몇월 몇일 인가요?

In [19]:
dif_temp = -999 # 일교차
dif_date = '' # 일교차
# 날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃)
for row in seoul:
    if row[3] != -999 and row[4] != 999 and (row[4]-row[3]) >= dif_temp:
        dif_temp = row[4]-row[3]
        dif_date = row[0]
#         print(dif_date, dif_temp)
        
print(dif_date, dif_temp)

1942-04-19 21.8

### for문 안쓰고 풀기

In [48]:
seoul2 = np.loadtxt("./data/seoul.csv", dtype=np.object, 
                 delimiter=',', skiprows=1)

print(seoul2)

[['1907-10-01' '108' '13.5' '7.9' '20.7']
 ['1907-10-02' '108' '16.2' '7.9' '22']
 ['1907-10-03' '108' '16.2' '13.1' '21.3']
 ...
 ['2020-09-04' '108' '23.3' '19.9' '27.5']
 ['2020-09-05' '108' '23.3' '19.2' '27.3']
 ['2020-09-06' '108' '21.7' '19.5' '24.4']]

In [58]:
print(seoul2[:,3]) # ['7.9' '7.9' '13.1' ... '19.9' '19.2' '19.5']

empty_low_idx = np.where(seoul2[:,3]=='')
seoul2 = np.delete(seoul2, empty_low_idx, axis=0)  # 최저기온 "" 행 제거
empty_high_idx = np.where(seoul2[:,4]=='')
seoul2 = np.delete(seoul2, empty_high_idx, axis=0)  # 최고기온 "" 행 제거

['7.9' '7.9' '13.1' ... '19.9' '19.2' '19.5']

In [69]:
a = (seoul2[:,-1].astype(np.float64) - seoul2[:,-2].astype(np.float64)).reshape(-1, 1)
print(a)
# [[12.8]
#  [14.1]
#  [ 8.2]
#  ...
#  [ 7.6]
#  [ 8.1]
#  [ 4.9]]

[[12.8]
 [14.1]
 [ 8.2]
 ...
 [ 7.6]
 [ 8.1]
 [ 4.9]]

In [68]:
result = np.concatenate((seoul2,(seoul2[:,-1].astype(np.float64) - seoul2[:,-2].astype(np.float64)).reshape(-1, 1)),axis=1) 
print(result)

[['1907-10-01' '108' '13.5' '7.9' '20.7' 12.799999999999999]
 ['1907-10-02' '108' '16.2' '7.9' '22' 14.1]
 ['1907-10-03' '108' '16.2' '13.1' '21.3' 8.200000000000001]
 ...
 ['2020-09-04' '108' '23.3' '19.9' '27.5' 7.600000000000001]
 ['2020-09-05' '108' '23.3' '19.2' '27.3' 8.100000000000001]
 ['2020-09-06' '108' '21.7' '19.5' '24.4' 4.899999999999999]]

In [71]:
max_high = result[:,-1].max() # 최대 온도
print(max_high)
print(result[:,0][result[:,-1] == max_high])

21.8
['1942-04-19']

## 3. 1년 중 평균적으로 일교차가 가장 큰 날짜는 몇월 몇일 인가요?

In [26]:
day = {}
for row in seoul:
    if row[0][5:] in day.keys():
        day[row[0][5:]][0] += row[4]-row[3]
        day[row[0][5:]][1] += 1
    else:
        day[row[0][5:]] = [row[4]-row[3], 1]

In [27]:
print(day)

{'10-01': [7127.299999999998, 112], '10-02': [7114.499999999995, 112], '10-03': [7138.399999999998, 112], '10-04': [7168.899999999999, 112], '10-05': [7198.700000000001, 112], '10-06': [7159.400000000001, 112], '10-07': [7163.600000000001, 112], '10-08': [7166.399999999998, 112], '10-09': [7210.100000000004, 112], '10-10': [7177.799999999998, 112], '10-11': [7168.000000000002, 112], '10-12': [8165.5, 112], '10-13': [7201.700000000002, 112], '10-14': [7212.000000000002, 112], '10-15': [7163.899999999996, 112], '10-16': [7192.4, 112], '10-17': [7179.399999999995, 112], '10-18': [7255.400000000003, 112], '10-19': [7256.300000000003, 112], '10-20': [7174.2, 112], '10-21': [7221.399999999999, 112], '10-22': [7222.900000000005, 112], '10-23': [7228.500000000001, 112], '10-24': [7184.500000000002, 112], '10-25': [7163.199999999999, 112], '10-26': [7169.599999999999, 112], '10-27': [7257.299999999997, 112], '10-28': [7134.999999999998, 112], '10-29': [7133.400000000001, 112], '10-30': [7168.2000000000035, 112], '10-31': [7172.0, 112], '11-01': [5150.9000000000015, 111], '11-02': [5160.699999999997, 111], '11-03': [5179.799999999998, 111], '11-04': [5135.499999999999, 111], '11-05': [5124.500000000001, 111], '11-06': [5108.700000000001, 111], '11-07': [5056.3, 111], '11-08': [5045.999999999999, 111], '11-09': [5038.799999999998, 111], '11-10': [4983.900000000005, 111], '11-11': [5042.199999999997, 111], '11-12': [5058.900000000001, 111], '11-13': [5012.900000000002, 111], '11-14': [5001.799999999999, 111], '11-15': [4965.299999999999, 111], '11-16': [5004.299999999998, 111], '11-17': [5005.099999999999, 111], '11-18': [5012.600000000001, 111], '11-19': [4989.400000000002, 111], '11-20': [5001.2, 111], '11-21': [4972.200000000001, 111], '11-22': [5016.699999999999, 111], '11-23': [4996.300000000002, 111], '11-24': [4950.5999999999985, 111], '11-25': [4970.099999999999, 111], '11-26': [4921.200000000003, 111], '11-27': [4982.299999999998, 111], '11-28': [4918.500000000001, 111], '11-29': [4897.200000000001, 111], '11-30': [4954.900000000003, 111], '12-01': [4954.2, 112], '12-02': [4922.3, 112], '12-03': [4931.799999999998, 112], '12-04': [4927.499999999999, 112], '12-05': [4939.5, 112], '12-06': [4950.000000000002, 112], '12-07': [4892.999999999996, 112], '12-08': [4906.900000000002, 112], '12-09': [4915.400000000001, 112], '12-10': [4897.599999999999, 112], '12-11': [4893.799999999997, 112], '12-12': [4935.900000000002, 112], '12-13': [4927.900000000004, 112], '12-14': [4866.4, 112], '12-15': [4875.799999999999, 112], '12-16': [4866.800000000002, 112], '12-17': [4935.699999999999, 112], '12-18': [4861.399999999998, 112], '12-19': [4897.100000000003, 112], '12-20': [4923.900000000002, 112], '12-21': [4895.2, 112], '12-22': [4896.9, 112], '12-23': [4894.699999999998, 112], '12-24': [4908.699999999998, 112], '12-25': [4917.099999999999, 112], '12-26': [4893.100000000001, 112], '12-27': [4848.899999999996, 112], '12-28': [4844.900000000001, 112], '12-29': [4907.800000000004, 112], '12-30': [4923.4, 112], '12-31': [4874.500000000003, 112], '01-01': [4864.100000000002, 112], '01-02': [4851.200000000003, 112], '01-03': [4915.400000000001, 112], '01-04': [4943.600000000001, 112], '01-05': [4921.499999999999, 112], '01-06': [4933.899999999999, 112], '01-07': [4907.800000000004, 112], '01-08': [4898.599999999999, 112], '01-09': [4950.500000000001, 112], '01-10': [4868.700000000004, 112], '01-11': [4922.9000000000015, 112], '01-12': [4940.299999999999, 112], '01-13': [4890.499999999997, 112], '01-14': [4935.400000000001, 112], '01-15': [4923.5, 112], '01-16': [4902.299999999999, 112], '01-17': [4924.200000000001, 112], '01-18': [4915.299999999999, 112], '01-19': [4917.300000000001, 112], '01-20': [4963.399999999999, 112], '01-21': [4938.799999999997, 112], '01-22': [4922.400000000001, 112], '01-23': [4910.699999999999, 112], '01-24': [4919.700000000001, 112], '01-25': [4918.8, 112], '01-26': [4913.0, 112], '01-27': [4969.799999999999, 112], '01-28': [4948.000000000002, 112], '01-29': [4924.0, 112], '01-30': [4964.300000000001, 112], '01-31': [4980.099999999999, 112], '02-01': [4956.800000000001, 112], '02-02': [5007.400000000003, 112], '02-03': [4975.200000000001, 112], '02-04': [4949.999999999997, 112], '02-05': [4929.7, 112], '02-06': [4948.500000000004, 112], '02-07': [4942.999999999999, 112], '02-08': [4940.299999999998, 112], '02-09': [4927.299999999998, 112], '02-10': [4944.500000000003, 112], '02-11': [4987.300000000005, 112], '02-12': [4966.900000000003, 112], '02-13': [5003.300000000002, 112], '02-14': [4948.199999999998, 112], '02-15': [4922.899999999999, 112], '02-16': [4959.1, 112], '02-17': [4954.099999999999, 112], '02-18': [4947.400000000005, 112], '02-19': [6989.200000000003, 112], '02-20': [4993.500000000003, 112], '02-21': [4974.099999999999, 112], '02-22': [5027.7, 112], '02-23': [4972.600000000002, 112], '02-24': [4988.700000000002, 112], '02-25': [4992.9, 112], '02-26': [5024.9, 112], '02-27': [4999.599999999999, 112], '02-28': [5009.099999999998, 112], '02-29': [2223.699999999999, 29], '03-01': [4987.100000000001, 112], '03-02': [5008.800000000002, 112], '03-03': [5030.300000000003, 112], '03-04': [5010.799999999999, 112], '03-05': [5009.800000000003, 112], '03-06': [4927.199999999999, 112], '03-07': [4961.9000000000015, 112], '03-08': [5026.500000000001, 112], '03-09': [5035.0, 112], '03-10': [4979.099999999998, 112], '03-11': [5014.899999999998, 112], '03-12': [5052.999999999998, 112], '03-13': [5016.1, 112], '03-14': [5044.300000000001, 112], '03-15': [5053.100000000003, 112], '03-16': [5038.299999999998, 112], '03-17': [5144.900000000002, 112], '03-18': [5105.200000000002, 112], '03-19': [5105.199999999996, 112], '03-20': [5085.999999999997, 112], '03-21': [5089.9000000000015, 112], '03-22': [5050.999999999997, 112], '03-23': [5063.099999999999, 112], '03-24': [5011.700000000002, 112], '03-25': [5030.0000000000055, 112], '03-26': [5136.900000000002, 112], '03-27': [5112.400000000001, 112], '03-28': [5117.200000000002, 112], '03-29': [5058.899999999999, 112], '03-30': [5089.000000000001, 112], '03-31': [5142.999999999997, 112], '04-01': [5203.700000000004, 112], '04-02': [5121.3, 112], '04-03': [5112.499999999998, 112], '04-04': [5183.800000000002, 112], '04-05': [5165.600000000001, 112], '04-06': [5162.4, 112], '04-07': [5136.400000000002, 112], '04-08': [5156.900000000001, 112], '04-09': [5170.299999999998, 112], '04-10': [5136.800000000001, 112], '04-11': [5190.200000000001, 112], '04-12': [5188.700000000001, 112], '04-13': [5164.600000000002, 112], '04-14': [5152.900000000003, 112], '04-15': [5243.899999999999, 112], '04-16': [5178.599999999999, 112], '04-17': [5204.700000000001, 112], '04-18': [5238.5, 112], '04-19': [5247.2999999999965, 112], '04-20': [5190.6, 112], '04-21': [5184.0, 112], '04-22': [5158.300000000001, 112], '04-23': [5258.000000000002, 112], '04-24': [5148.499999999998, 112], '04-25': [5214.099999999999, 112], '04-26': [5185.299999999998, 112], '04-27': [5199.800000000003, 112], '04-28': [5194.799999999999, 112], '04-29': [5310.9000000000015, 112], '04-30': [5202.599999999999, 112], '05-01': [5189.599999999998, 112], '05-02': [5174.4999999999945, 112], '05-03': [5168.999999999999, 112], '05-04': [5197.2, 112], '05-05': [5225.4000000000015, 112], '05-06': [5166.099999999998, 112], '05-07': [5234.399999999999, 112], '05-08': [5233.299999999999, 112], '05-09': [5205.9, 112], '05-10': [5188.7000000000035, 112], '05-11': [5150.500000000003, 112], '05-12': [5143.000000000003, 112], '05-13': [5154.300000000004, 112], '05-14': [5202.300000000001, 112], '05-15': [5206.800000000001, 112], '05-16': [5166.2, 112], '05-17': [5206.599999999999, 112], '05-18': [5121.400000000001, 112], '05-19': [5117.0999999999985, 112], '05-20': [5167.699999999999, 112], '05-21': [5210.5, 112], '05-22': [5235.399999999999, 112], '05-23': [5261.700000000001, 112], '05-24': [5197.599999999999, 112], '05-25': [5152.499999999998, 112], '05-26': [5207.099999999999, 112], '05-27': [5160.300000000001, 112], '05-28': [5220.1, 112], '05-29': [5184.300000000001, 112], '05-30': [5213.899999999995, 112], '05-31': [5238.499999999997, 112], '06-01': [5181.299999999996, 112], '06-02': [5156.899999999998, 112], '06-03': [5111.800000000001, 112], '06-04': [5141.7999999999965, 112], '06-05': [5149.200000000002, 112], '06-06': [5171.200000000001, 112], '06-07': [5145.200000000001, 112], '06-08': [5109.199999999998, 112], '06-09': [5129.399999999995, 112], '06-10': [5070.500000000003, 112], '06-11': [5095.4000000000015, 112], '06-12': [5074.7, 112], '06-13': [5128.8, 112], '06-14': [5121.100000000001, 112], '06-15': [5106.500000000001, 112], '06-16': [5094.2999999999965, 112], '06-17': [5052.799999999999, 112], '06-18': [5038.500000000005, 112], '06-19': [5048.099999999998, 112], '06-20': [5041.200000000001, 112], '06-21': [5103.300000000001, 112], '06-22': [5059.0, 112], '06-23': [5063.000000000001, 112], '06-24': [5028.199999999998, 112], '06-25': [4973.500000000002, 112], '06-26': [4940.599999999999, 112], '06-27': [4942.499999999997, 112], '06-28': [4939.800000000003, 112], '06-29': [4932.100000000002, 112], '06-30': [4907.700000000002, 112], '07-01': [4871.5999999999985, 112], '07-02': [4874.4000000000015, 112], '07-03': [4844.4, 112], '07-04': [4802.300000000001, 112], '07-05': [4889.7, 112], '07-06': [4864.400000000001, 112], '07-07': [4862.399999999999, 112], '07-08': [4838.699999999999, 112], '07-09': [4833.6, 112], '07-10': [4788.6, 112], '07-11': [4787.500000000002, 112], '07-12': [4767.1, 112], '07-13': [4810.7, 112], '07-14': [4777.100000000003, 112], '07-15': [4788.399999999997, 112], '07-16': [4750.700000000001, 112], '07-17': [4778.299999999999, 112], '07-18': [4817.600000000001, 112], '07-19': [4775.999999999996, 112], '07-20': [4783.8, 112], '07-21': [4744.500000000003, 112], '07-22': [4789.2, 112], '07-23': [4782.699999999998, 112], '07-24': [4801.399999999999, 112], '07-25': [4788.499999999998, 112], '07-26': [4816.200000000004, 112], '07-27': [4789.100000000001, 112], '07-28': [4764.9000000000015, 112], '07-29': [4785.600000000001, 112], '07-30': [4808.5999999999985, 112], '07-31': [4849.899999999998, 112], '08-01': [2835.900000000001, 111], '08-02': [2807.0999999999995, 111], '08-03': [2840.0999999999995, 111], '08-04': [2813.6999999999994, 111], '08-05': [2885.0000000000005, 111], '08-06': [2861.6999999999994, 111], '08-07': [2861.9999999999986, 111], '08-08': [2872.6999999999975, 111], '08-09': [2887.0000000000005, 111], '08-10': [2871.4999999999995, 111], '08-11': [2884.999999999999, 111], '08-12': [2894.4, 111], '08-13': [2894.4999999999986, 111], '08-14': [2873.3000000000015, 111], '08-15': [2879.8999999999987, 111], '08-16': [2868.299999999999, 111], '08-17': [2890.599999999999, 111], '08-18': [2896.599999999998, 111], '08-19': [2898.7999999999975, 111], '08-20': [2863.400000000001, 111], '08-21': [2893.7999999999984, 111], '08-22': [2896.600000000001, 111], '08-23': [2901.0, 111], '08-24': [2883.4, 111], '08-25': [2875.2000000000007, 111], '08-26': [2881.0999999999985, 111], '08-27': [2840.8999999999996, 111], '08-28': [2881.5, 111], '08-29': [2849.2000000000016, 111], '08-30': [2881.8000000000006, 111], '08-31': [2914.100000000001, 111], '09-01': [6929.0, 112], '09-02': [6887.599999999999, 112], '09-03': [6886.699999999998, 112], '09-04': [6895.999999999999, 112], '09-05': [6929.700000000002, 112], '09-06': [6956.999999999995, 112], '09-07': [6967.399999999997, 111], '09-08': [6953.1, 111], '09-09': [6931.000000000003, 111], '09-10': [6984.399999999999, 111], '09-11': [6939.500000000001, 111], '09-12': [6969.6, 111], '09-13': [7006.099999999999, 111], '09-14': [7011.100000000002, 111], '09-15': [7014.600000000005, 111], '09-16': [7054.4000000000015, 111], '09-17': [7052.199999999998, 111], '09-18': [7060.400000000001, 111], '09-19': [7069.2999999999965, 111], '09-20': [7084.999999999997, 111], '09-21': [7092.300000000003, 111], '09-22': [7139.099999999998, 111], '09-23': [7110.999999999998, 111], '09-24': [7076.899999999999, 111], '09-25': [7099.6, 111], '09-26': [5099.599999999999, 110], '09-27': [5133.100000000003, 110], '09-28': [5090.500000000001, 110], '09-29': [5099.300000000002, 110], '09-30': [5113.900000000003, 110]}

In [ ]:
# 대구
# 날짜,지점,평균기온(℃),최저기온(℃),최고기온(℃)
for row in daegu:
    if row[2] == '': # 평균기온
        row[2] = -999      
    else:
        row[2] = float(row[2]) 
    if row[3] == '': # 최저기온
        row[3] = -999      
    else:
        row[3] = float(row[3]) 
    if row[4] == '': # 최고기온
        row[4] = 999      
    else:
        row[4] = float(row[4]) 

print(daegu)